import bcrypt from "bcrypt";
const data = {
  users: [
    {
      name: "Eleanor Shellstrop",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Chidi Anagonye",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 10,
    },
    {
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/image/p2.jpg",
      price: 100,
      brand: "Adidas",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
      countInStock: 20,
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/image/p3.jpg",
      price: 220,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
      countInStock: 0,
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/image/p4.jpg",
      price: 78,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
      countInStock: 15,
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/image/p5.jpg",
      price: 65,
      brand: "Puma",
      rating: 3,
      numReviews: 14,
      description: "high quality product",
      countInStock: 5,
    },
    {
      name: "Adidas Slim Pant",
      category: "Pants",
      image: "/image/p6.jpg",
      price: 139,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
      countInStock: 12,
    },
  ],
};

export default data;
