export const USER_SIGNIN_REQUEST = "USER-SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER-SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER-SIGNIN_FAILURE";
export const USER_SIGNOUT = "USER_SIGNOUT";
